### ISSUE TITLE
[Improvement] Application environment handling

### ISSUE THREAD

**Issue by minhnimble** [Shayokh144/SurveyApp#3]
As per our our API [documentation](https://github.com/nimblehq/nimble-survey-web/wiki/REST-API#ios), there are more environments that our API should be able to support, which are Staging and Production, and you only handled the Production environment so far. I would like to know more on if you have any experiences in handling the CI/CD for different environments and if yes, how can CI/CD help us in such cases?

At the same time, it would be great if you could update the project implementation to handle both environments and point to the correct base endpoint for each environment as well. What do you think?

**Comment by Shayokh144** [comment]
In the requirement document it was written that "Make sure that you use the production URLs". So, I have only used the production url. May be I misunderstood. In case of maintaining different environment I can create multiple scheme's in XCODE and the add some compilation condition flags to check in code. I know this is not the best solution. There are Fastlane, Jenkins and other CI/CD tool. But unfortunately I didn't use those, as we use our own tools and in my current organisation I don't have the access to the CI/CD pipeline as separate devOps team managed that.  This is one of the reasons that I am looking for new opportunities, so that I can learn every sector properly.

**Comment by minhnimble** [comment]
> In the requirement document it was written that "Make sure that you use the production URLs". So, I have only used the production url. May be I misunderstood. In case of maintaining different environment I can create multiple scheme's in XCODE and the add some compilation condition flags to check in code. I know this is not the best solution. There are Fastlane, Jenkins and other CI/CD tool. But unfortunately I didn't use those, as we use our own tools and in my current organisation I don't have the access to the CI/CD pipeline as separate devOps team managed that. This is one of the reasons that I am looking for new opportunities, so that I can learn every sector properly.

→ No worries, it is true that using the production URL is a must because right now our server only supports the Production one, not Staging. At the same time, I just want to know more on how you would handle to support other environments as well when requested. From your answer I did have an overall view of your skills on this part already 👍
