### ISSUE TITLE
[Bug] [UI] The skeleton loading view doesn't match with design

### ISSUE THREAD

**Issue by minhnimble** [Shayokh144/SurveyApp#7]
## Why

The application needs to show the initial skeleton loading view with animation after first entering the app with a valid logged in session like design. Currently there are a few problems with the initial skeleton loading screen:
- The skeleton loading view doesn't animate and just stay static.
- The color and corner radius of the skeleton items doesn't match with the design and there is no gradient feeling.
- The next button in the bottom right corner is not shown correctly in circle shape on small screen devices (iPhone 5/SE, etc.).

## Acceptance Criteria
- The skeleton loading view needs to look like the following design with proper animation while it is being shown:

<img src="https://user-images.githubusercontent.com/70877098/159680292-df2c41e9-49af-4a0f-bc86-2b71cfe69433.png" width="300">

## Actual:

<img src="https://user-images.githubusercontent.com/70877098/159679848-faf71c6d-fb68-48be-8c32-e4ec13abf6f2.png" width="300">

**Comment by Shayokh144** [comment]
this issue is fixed with the commit : https://github.com/Shayokh144/SurveyApp/commit/2d34e87dd3e70498d8c1a3a30d876b84fdc9456b

- animation added with gradiant
- color and corner radius fixed
- next button removed according to given ui, other top element not added as those are not included in requiremen

**Comment by minhnimble** [comment]
Looks good to me 🚀
